sudo: required
language: generic
services: 
  - docker 

before_install:
  - docker build -t obusorezekiel/react-test -f ./client/Dockerfile.dev .
  - docker build myotherproject

script:
  - docker run -e CI=true obusorezekiel/react-test npm test

after_success:
  - docker build -t obusorezekiel/multi-client ./client
  - docker build -t obusorezekiel/multi-nginx ./nginx
  - docker build -t obusorezekliel/multi-server ./server
  - docker build -t obusorezekiel/multi-worker ./worker

  - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push obusorezekiel/multi-client
  - docker push obusorezekiel/multi-nginx
  - docker push obusorezekiel/multi-server
  - docker push obusorezekiel/multi-worker